### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by morths** [MitsuhaYuki/yuki-emby-crack#1]
Hi! I don't know if this actually works but everytime i try to run 'main.exe' i get a "Fatal Error!" message which states: 'Failed to execute script main'. Anyone else has this issue? I try to run 'main.exe' on windows server 2012 (on which my emby server is installed). thnx.

**Comment by MitsuhaYuki** [comment]
I can't reproduce this error, could you please run this program in CMD? By doing this you will get a stacktrace which will help to solve this problem.

**Comment by morths** [comment]
I ran from CMD "main.exe > log.txt 2> errorlog.txt" and got (in errorlog.txt):

Traceback (most recent call last):
  File "main.py", line 73, in <module>
  File "tornado\tcpserver.py", line 151, in listen
  File "tornado\netutil.py", line 174, in bind_sockets
OSError: [WinError 10013] \u0388\u03b3\u03b9\u03bd\u03b5 \u03c0\u03c1\u03bf\u03c3\u03c0\u03ac\u03b8\u03b5\u03b9\u03b1 \u03c0\u03c1\u03cc\u03c3\u03b2\u03b1\u03c3\u03b7\u03c2 \u03c3\u03b5 \u03c5\u03c0\u03bf\u03b4\u03bf\u03c7\u03ae \u03bc\u03b5 \u03c4\u03c1\u03cc\u03c0\u03bf \u03c0\u03bf\u03c5 \u03b4\u03b5\u03bd \u03b5\u03c0\u03b9\u03c4\u03c1\u03ad\u03c0\u03b5\u03c4\u03b1\u03b9 \u03b1\u03c0\u03cc \u03c4\u03b1 \u03b4\u03b9\u03ba\u03b1\u03b9\u03ce\u03bc\u03b1\u03c4\u03b1 \u03c0\u03c1\u03cc\u03c3\u03b2\u03b1\u03c3\u03b7\u03c2

I hope it helps..

**Comment by morths** [comment]
The text after [WinError 10013] should be translated in english as "An attempt was made to access a socket in a way forbidden by its access permissions".

For some reason cmd parsed strangely my native language (greek) into the txt file..

**Comment by MitsuhaYuki** [comment]
Thanks for your reply, but it seems this error indicates that 80 or 443 port on your machine is occupied or disabled. The principle of this program is to set up a fake "mb3admin.com" web site and return active info. If you are already use some web server like nginx or apache, you can set them to direct response the active info for corresponding url(which you can find those url and response in [here](https://github.com/MitsuhaYuki/yuki-emby-crack/blob/master/main.py)).

**Comment by morths** [comment]
Yes, i believe both ports (80 & 443) are occupied by my 'Windows Server 2012 R2 Essentials Remote Web Access' which if reached outside of my network (from a certain domain provided by microsoft - something.remotewebaccess.com) end up at a page like this: https://cybersafenv.org/wp-content/uploads/2019/09/isc-20190924-1.png

Isn't there any way to run the exe without having to mess with Remote Web Access (which i totally need) or its ports? Because even if the second part of your answer is indeed applicable on my remote web access somehow, i am not quite sure how to do it...

**Comment by MitsuhaYuki** [comment]
...Maybe? But an alternative way is to run this program on another machine B(can be a virtual machine) with those ports open , and change machine A's host file to `mb3admin.com Machine B's IP`. I think this way is relatively easy to do than other ways, but will consume more resource.

**Comment by morths** [comment]
OK. I'll try the ports first and if i can't manage i'll try with a virtual machine.. In any case i'll post back the results as soon as possible. thnx.

**Comment by morths** [comment]
Sorry for not posting back for sooo long, but i didn't had much time to explore this.. Last week i finally managed to bypass the error by instructing my server to get a secong local ip via TCP/IP setting (and then disengage this ip from IIS Manager). After that.. voila!, 'main.exe' started successfully!

I also had to manually install the certificate you provide to the machine the 'main.exe' is running (the server in my case) and also open emby dashboard from the same machine ONLY! (ie the machine 'main.exe' is running) and enter a fake key in emby premiere section, in order to get the "lifetime subscription message" (the part with the key was tricky as you don't mention it in your instructions.. - at first i was trying to enter key from another machine but that didn't work.. i was getting a message about wrong key).

Only thing is that this whole setup doesn't work for sure with my lg tv's webos emby client (Emby Theater 1.0.24), for which i mainly wanted emby.. i tried everything.. i have even setup my lg tv (through dns) to only open my local fake 'mb3admin.com' when requested from the tv (i double checked this from lg tv's browser), but it seems that the script included in "main.exe", isn't covering emby's webos client, although it should because i believe it also contacts 'mb3admin.com'..

Anyway thank you for this nice little trick! I confirm it works as described (on windows), except the webos emby client of course. (i don't know about other clients, such as android)

**Comment by MitsuhaYuki** [comment]
For the convenience of presentation, the machine running `main.exe` is referred to as `server`, and all other clients (PC, Android, TV or Emby Dashboard) are referred to as `clients`.

In fact, all clients needs activation, which means the client machine need install the CA license and make '`mb3admin.com`' point to the server's IP in your local network. So it is possible to open emby dashboard in another machine's browser, all you need is install license and edit the host file. But if you use some proxy plugins like 'SwitchyOmega', you'll also need to change the plugin's config to make sure the 'mb3admin.com' is properly redirect to the server's IP. By the way, because of the browser cache, sometimes even you configured it properly you could also have chance to get a wrong result. So using 'inprivate' mode to debug this whole thing is recommended.

For Android client, it is also the same method, install the CA license and make '`mb3admin.com`' point to the server's IP. You can use some VPN tools like `Clash for Android` to help you achieve the purpose of modifying the host and does not require root permissions.

Hopefully the above answers can help you, thank you for your comment!

**Comment by morths** [comment]
Actually i had figured that much, but unfortunately "webos" (which is lg tvs operating system - as android is the operating system for other devices) is a very 'difficult' os, unlike android which is more flexible. I truly believe that if my tv were andoid-based i would have managed it somehow.. (with your instructions or otherwise)
Blame me for investing in lg tvs in my home network..

The only thing i have managed to do, is to succesfully point the tv to my fake local 'mb3admin.com' for all 'mb3admin.com' requests coming from the tv. I even confirmed the successful redirection from the tv's browser. **The thing is**, that every single time, just before the browser gives me the 'emby validation server successfully start' or '{"cacheExpirationDays": 365, "message": "Device Valid", "resultCode": "GOOD"}' messages, it gives me a "the server's security certificate is not valid" message which doesn't procceed further unless i hit a "continue anyway" button. Only after i hit this button i get the messages from the fake 'mb3admin.com'.

So i suspect that because the lg tv emby client app can't bypass somehow that ssl error (like i manually bypass it in the browser by hitting 'continue anyway' button), it just thinks it hasn't access to 'mb3admin.com' and won't unlock me premiere features.. The same thing also happens when i open emby from lg tv's browser (i.e. not using the lg tv emby client app). It opens without premiere features unlocked (although it should because all 'mb3admin.com' requests from tv are pointed to the fake 'mb3admin.com' on my server's local ip).

You'll probably tell me that it has to do with the certificate on lg tv.. Yes, that is what i am thinking too, but unfortunately there is no way to install any certificate on lg tv & its os (webos)... 

anyway thnx for the additional instructions and sorry for long post!
