### ISSUE TITLE
It shows you have lifetime emby premiere plan but on other devices with admin account will not give premiere features and will show "get premiere button:

### ISSUE THREAD

**Issue by prolexgreen** [MitsuhaYuki/yuki-emby-crack#7]
Title

**Comment by MitsuhaYuki** [comment]
The principle of this program is setup an activation server, and all emby clients(include emby server) will ask activation server for product active info. But all clients will do this separately, so other devices won't get emby premiere plan. You can change your router's host configuration to make all request to 'mb3admin.com' redirect to your activation server's ip, and install ssl certification on each device.
